version: '3.8'

services:
  minecraft:
    image: h1ggsk/catfacts-rust:latest
    container_name: catfacts_rust
    restart: unless-stopped
    mem_limit: 400m
    env_file: .env
    volumes:
      - ./data:/data
      - ./data/azalea-auth:/root/.cache/azalea

  discord:
    image: h1ggsk/catfacts-discord:latest
    container_name: catfacts_discord
    restart: unless-stopped
    mem_limit: 400m
    env_file: .env
    volumes:
      - ./data:/data
    command: python bot.py

  web:
    image: h1ggsk/catfacts-web:latest
    container_name: catfacts_web
    restart: unless-stopped
    mem_limit: 400m
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    command: uvicorn web:app --host 0.0.0.0 --port 8000