services:
  web:
    build: ./python
    command: uvicorn web:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    mem_limit: 400m
    restart: unless-stopped

  discord:
    build: ./python
    command: python bot.py
    volumes:
      - ./data:/data
    env_file: .env
    mem_limit: 400m
    restart: unless-stopped

  minecraft:
    build: ./rust_bot
    volumes:
      - ./data:/data
      - ./rust_bot_cache:/.azalea
    env_file: .env
    mem_limit: 400m
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - web

volumes:
  data: