services:
  minecraft:
    image: h1ggsk/catfacts-rust:latest
    container_name: catfacts_rust
    restart: unless-stopped
    mem_limit: 400m
    env_file: .env
    environment:
      - XDG_CACHE_HOME=/data
    volumes:
      - ./data:/data

  discord:
    image: h1ggsk/catfacts-discord:latest
    container_name: catfacts_discord
    restart: unless-stopped
    mem_limit: 400m
    env_file: .env
    volumes:
      - ./data:/data
    command: python bot.py

  web:
    image: h1ggsk/catfacts-web:latest
    container_name: catfacts_web
    restart: unless-stopped
    mem_limit: 400m
    volumes:
      - ./data:/data
    command: uvicorn web:app --host 0.0.0.0 --port 8000

  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - web